name: Pokemon Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Bulbasaur tests
        run: npm test -- --testNamePattern="fetchBulbasaurData"

      - name: Run Charmander tests
        run: npm test -- --testNamePattern="fetchCharmanderData"

      - name: Run Squirtle tests
        run: npm test -- --testNamePattern="fetchSquirtleData"

      - name: Run Ivysaur tests
        run: npm test -- --testNamePattern="fetchIvysaurData"
