name: Autograding Tests
'on':
  workflow_dispatch:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Bulbasaur tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Bulbasaur Tests
          setup-command: npm install
          command: npm test -- --testNamePattern="fetchBulbasaurData"
          timeout: 10
          max-score: 25

      - name: Run Charmander tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Charmander Tests
          setup-command: npm install
          command: npm test -- --testNamePattern="fetchCharmanderData"
          timeout: 10
          max-score: 25

      - name: Run Squirtle tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Squirtle Tests
          setup-command: npm install
          command: npm test -- --testNamePattern="fetchSquirtleData"
          timeout: 10
          max-score: 25

      - name: Run Ivysaur tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Ivysaur Tests
          setup-command: npm install
          command: npm test -- --testNamePattern="fetchIvysaurData"
          timeout: 10
          max-score: 25
